-- return
--
-- { "elihunter173/dirbuf.nvim", lazy = false },
-- {
--   "preservim/vim-pencil",
--   cmd = {
--     "Pencil",
--     "PencilOff",
--     "PencilToggle",
--     "PencilSoft",
--     "PencilHard",
--   },
--
--   ft = { "text", "markdown", "plaintex" },
--   config = function()
--     vim.api.nvim_create_autocmd({ "BufEnter" }, {
--       pattern = { "*.md", "*.txt", "*.tex" },
--       command = "PencilSoft",
--     })
--   end,
-- },
--
-- { "atiladefreitas/dooing",
--   cmd = { "Dooing" },
--   keys = { "<leader>td" }
-- },
